### ISSUE TITLE
AudioSegment.from_mp3 error

### ISSUE THREAD

**Issue by dreinstein10** [gullu26/RedditToYouTubeBot#1]
Hi, I'm trying to run your scripts but I get an error from the function:  _AudioSegment.from_mp3('./res/voice/' + voice)_

I opened the folder and I can see that the file ('0-0-0-a.mp3') is there, but it's still not recognized by this function. Have you seen this error before? Am I missing something?

Here's the error I get...

> Traceback (most recent call last):
>   File "D:\PROYECTOS\VisionMW\RedditToYouTubeBot-master\RedditToYouTubeBot-master\RedditToYouTubeBot.py", line 389, in <module>
>     makeVid(audioTimes, 'res/images', i, postTitles[i])
>   File "D:\PROYECTOS\VisionMW\RedditToYouTubeBot-master\RedditToYouTubeBot-master\RedditToYouTubeBot.py", line 83, in makeVid
>     mergeAudio(video_name, qNum, title)
>   File "D:\PROYECTOS\VisionMW\RedditToYouTubeBot-master\RedditToYouTubeBot-master\RedditToYouTubeBot.py", line 107, in mergeAudio
>     audioFile += AudioSegment.from_mp3('./res/voice/' + voice)
>   File "C:\Users\chuy_\AppData\Local\Programs\Python\Python37\lib\site-packages\pydub\audio_segment.py", line 716, in from_mp3
>     return cls.from_file(file, 'mp3', parameters=parameters)
>   File "C:\Users\chuy_\AppData\Local\Programs\Python\Python37\lib\site-packages\pydub\audio_segment.py", line 665, in from_file
>     info = mediainfo_json(orig_file)
>   File "C:\Users\chuy_\AppData\Local\Programs\Python\Python37\lib\site-packages\pydub\utils.py", line 263, in mediainfo_json
>     res = Popen(command, stdin=stdin_parameter, stdout=PIPE, stderr=PIPE)
>   File "C:\Users\chuy_\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 775, in __init__
>     restore_signals, start_new_session)
>   File "C:\Users\chuy_\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1178, in _execute_child
>     startupinfo)
> FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by dreinstein10** [comment]
Nevermind, I just needed to add ffmpeg path to the "environment variables".
